image : python:2

before_script:
  - apt-get update -qq && apt-get install -y -qq python-pip pandoc
  - pip install numpy
  - pip install -r requirements.txt
  - pip install -e .

flake8:
  script:
    - flake8 .

pytest:
  script:
    - cd test
    - export RENOM_PRECISION=64
    - py.test
    - export RENOM_PRECISION=32
    - py.test

